// Turns the sanity proof produced by build.sh (build/proof.json + build/public.json) into
// contracts/test/fixtures/proof_ok.json, the fixture consumed by Registry.t.sol (PRD 5.4).
// Includes the Solidity calldata form (hex) and the grid parameters the contract test must register.

const fs = require("fs");
const path = require("path");
const snarkjs = require("snarkjs");
const { buildFixture, GRID, CLEAN_CELL, SEASON, EXPORTER_ADDRESS } = require("../test/helpers/fixture");

const BUILD = path.join(__dirname, "..", "build");
const OUT = path.join(__dirname, "..", "..", "contracts", "test", "fixtures", "proof_ok.json");

async function main() {
  const proof = JSON.parse(fs.readFileSync(path.join(BUILD, "proof.json"), "utf8"));
  const publicSignals = JSON.parse(fs.readFileSync(path.join(BUILD, "public.json"), "utf8"));

  const fx = await buildFixture();
  const expectedNullifier = fx.nullifierFor(CLEAN_CELL.row, CLEAN_CELL.col).toString();
  if (publicSignals[0] !== expectedNullifier) throw new Error("public nullifier != fixture nullifier");
  if (publicSignals[1] !== fx.tree.root.toString()) throw new Error("public root != fixture root");

  // snarkjs returns `pA,pB,pC,pubSignals` as a comma-separated list of JSON arrays (hex strings).
  const calldataStr = await snarkjs.groth16.exportSolidityCallData(proof, publicSignals);
  const [pA, pB, pC, pubSignals] = JSON.parse(`[${calldataStr}]`);

  const toHex32 = (dec) => "0x" + BigInt(dec).toString(16).padStart(64, "0");

  const fixture = {
    _comment:
      "Generated by circuits/build.sh via scripts/make_fixture.js. Valid Groth16 proof for the synthetic " +
      "4x4 test grid; public signal order is [nullifier, root, season, exporter, lat0S, lon0S, stepS].",
    proof,
    publicSignals,
    calldata: { pA, pB, pC, pubSignals },
    grid: {
      root: toHex32(fx.tree.root),
      lat0S: GRID.lat0S,
      lon0S: GRID.lon0S,
      stepS: GRID.stepS,
      cols: GRID.cols,
      rows: GRID.rows,
      depth: GRID.depth,
    },
    season: SEASON,
    exporter: EXPORTER_ADDRESS,
    nullifier: toHex32(publicSignals[0]),
    cell: { ...CLEAN_CELL, note: "test data only; a real farmer's cell is never published" },
  };

  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, JSON.stringify(fixture, null, 2) + "\n");
  console.log(`wrote ${path.relative(process.cwd(), OUT)}`);
}

main().then(() => process.exit(0), (e) => { console.error(e); process.exit(1); });
